"""Core reward computation for teacher/student logprob comparison.

This module provides ``_compute_token_rewards``, which compares student and
teacher log probabilities at each generation position to produce
per-position reward information used in on-policy distillation training.

The reward at each candidate is ``student_logp - teacher_logp``, which
measures how much more (or less) likely the student considers a token
compared to the teacher.  Positive values indicate the student
over-estimates the token relative to the teacher; negative values
indicate under-estimation.

Example
-------
>>> # Typically called inside a distillation workflow
>>> rewards = await _compute_token_rewards(
...     student_output_ids=[200, 201],
...     student_input_ids=[100, 101, 102],
...     student_top_k_logprobs=[
...         [(200, -0.5), (300, -1.2), (400, -2.0)],
...         [(201, -0.3), (500, -0.8), (600, -1.5)],
...     ],
...     teacher_client=client,
...     top_k=3,
... )
"""

from __future__ import annotations

from customized_areal.tree_search.distilling.distill_types import PositionRewardInfo

from areal.utils import logging

from .teacher_client import TeacherClient

logger = logging.getLogger("RewardCompute")


async def _compute_token_rewards(
    student_output_ids: list[int],
    student_input_ids: list[int],
    student_top_k_logprobs: list[list[tuple[int, float]]],
    teacher_client: TeacherClient,
    top_k: int = 10,
) -> list[PositionRewardInfo]:
    """Compute per-position rewards from student vs teacher logprobs.

    For each output position, the student's top-k candidate tokens are
    sent to the teacher model to obtain teacher log probabilities.  The
    reward for each candidate is then computed as
    ``student_logp - teacher_logp``.

    Parameters
    ----------
    student_output_ids : list[int]
        Token IDs actually generated by the student model.
    student_input_ids : list[int]
        Token IDs of the prompt/prefix fed to the student model.
    student_top_k_logprobs : list[list[tuple[int, float]]]
        For each output position, a list of ``(token_id, logprob)``
        tuples from the student.  Shape:
        ``[num_positions][num_candidates]``.
    teacher_client : TeacherClient
        An open ``TeacherClient`` instance for querying teacher logprobs.
    top_k : int, optional
        Maximum number of candidate tokens per position to consider from
        the student's top-k logprobs.  Defaults to 10.

    Returns
    -------
    list[PositionRewardInfo]
        One ``PositionRewardInfo`` per output position, containing
        candidate token IDs, student logprobs, rewards, and the index
        of the actually-chosen token.  Returns an empty list if inputs
        are empty.
    """
    # Handle empty inputs.
    if not student_output_ids or not student_top_k_logprobs:
        return []

    # Build candidate_token_ids from student top-k, truncated to *top_k*.
    # The chosen (actually-generated) token is always placed at index 0 so
    # that logprobs[:, 0] in the standard GRPO loss path uses the correct token.
    candidate_token_ids: list[list[int]] = []
    for i, pos_logprobs in enumerate(student_top_k_logprobs):
        chosen_tid = student_output_ids[i]
        candidates = [chosen_tid] + [
            tid for tid, _ in pos_logprobs[:top_k] if tid != chosen_tid
        ]
        candidate_token_ids.append(candidates)

    # Query the teacher for logprobs of the candidate tokens.
    teacher_logprobs_per_pos: list[
        dict[int, float]
    ] = await teacher_client.get_logprobs_for_candidates(
        input_ids=student_input_ids,
        output_ids=student_output_ids,
        candidate_token_ids=candidate_token_ids,
    )

    missing_logprob = teacher_client.config.teacher_missing_logprob

    # Build PositionRewardInfo for each position.
    results: list[PositionRewardInfo] = []
    for i, (pos_candidates, pos_student_logprobs) in enumerate(
        zip(candidate_token_ids, student_top_k_logprobs)
    ):
        teacher_map = teacher_logprobs_per_pos[i]

        # Build student logprob lookup from the truncated candidate list.
        student_lp_lookup: dict[int, float] = {}
        for tid, lp in pos_student_logprobs[:top_k]:
            student_lp_lookup[tid] = lp

        # Compute rewards and gather per-candidate data.
        rewards: list[float] = []
        student_lps: list[float] = []
        teacher_lps: list[float] = []
        for tid in pos_candidates:
            s_lp = student_lp_lookup[tid]
            t_lp = teacher_map.get(tid, missing_logprob)
            student_lps.append(s_lp)
            teacher_lps.append(t_lp)
            rewards.append(s_lp - t_lp)

        # Determine the index of the actually-generated token.
        chosen_tid = student_output_ids[i]
        try:
            chosen_index = pos_candidates.index(chosen_tid)
        except ValueError:
            # Shouldn't happen in practice; default to 0.
            logger.warning(
                "Chosen token %d not found in candidates at position %d; "
                "defaulting chosen_index to 0.",
                chosen_tid,
                i,
            )
            chosen_index = 0

        results.append(
            PositionRewardInfo(
                position=i,
                candidates=[str(tid) for tid in pos_candidates],
                candidate_token_ids=list(pos_candidates),
                logprobs=student_lps,
                teacher_logprobs=teacher_lps,
                rewards=rewards,
                chosen_index=chosen_index,
            )
        )

    logger.debug("Computed token rewards for %d positions.", len(results))
    return results


__all__ = ["_compute_token_rewards"]
